# Generated by Django 5.2.4 on 2025-07-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recordings",
            "0002_alter_recording_options_alter_recording_audio_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="analysis",
            field=models.TextField(default="", verbose_name="ai分析"),
        ),
    ]
