# Generated by Django 5.2.4 on 2025-08-20 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0003_recording_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingGroup",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, unique=True, verbose_name="录音组"
                    ),
                ),
                ("analysis", models.TextField(default="", verbose_name="ai分析")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("group", models.ManyToManyField(to="recordings.recording")),
            ],
            options={
                "verbose_name": "录音组",
                "verbose_name_plural": "录音组",
            },
        ),
    ]
