# Generated by Django 5.2.4 on 2025-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0004_recordinggroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recording",
            name="id",
        ),
        migrations.AddField(
            model_name="recording",
            name="Id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
