# Generated by Django 5.2.4 on 2025-08-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0005_remove_recording_id_recording_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordinggroup",
            name="audio_file",
            field=models.FileField(
                default="", upload_to="recordinggroup/%Y/%m/%d/", verbose_name="音频文件"
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="audio_file",
            field=models.FileField(
                default="", upload_to="recordings/%Y/%m/%d/", verbose_name="音频文件"
            ),
        ),
    ]
