# Generated by Django 5.2.4 on 2025-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0006_recordinggroup_audio_file_alter_recording_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordinggroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("unanalyzed", "未分析"),
                    ("analyzing", "分析中"),
                    ("completed", "分析完成"),
                    ("failed", "分析失败"),
                ],
                default="unanalyzed",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="recordinggroup",
            name="audio_file",
            field=models.FileField(
                blank=True,
                default="",
                null=True,
                upload_to="recordinggroup/%Y/%m/%d/",
                verbose_name="音频文件",
            ),
        ),
    ]
